name: Direct Deploy to Production

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  test_and_build:
    name: Test and Build
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: 23
          distribution: temurin
          cache: maven

      - name: Run unit tests
        run: mvn test

      - name: Package the application
        run: mvn -B package -DskipTests

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: target/*.jar

  deploy_to_production:
    name: Deploy to Production VPS
    runs-on: ubuntu-latest
    needs: test_and_build
    if: github.event.pull_request.merged == true

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build

      - name: Deploy application to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            set -e
            echo "Starting deployment on Production VPS..."
            
            # Prepare deployment directory
            mkdir -p ${{ secrets.PROD_DEPLOY_PATH }}
            cd ${{ secrets.PROD_DEPLOY_PATH }}
            
            # Upload the JAR file
            rm -f app.jar
            mv ~/download/artifacts/*.jar app.jar
            
            # Stop the running application, if necessary
            if [[ -f app.pid ]]; then
              if ps -p $(cat app.pid) > /dev/null; then
                echo "Stopping the current running application..."
                kill -9 $(cat app.pid)
              fi
              rm -f app.pid
            fi
            
            # Start the new application
            echo "Starting the new application..."
            nohup java -jar app.jar --spring.profiles.active=prod > app.log 2>&1 &
            echo $! > app.pid
            
            echo "Deployment completed successfully!"